services:
  #  ok
  nacos:
    image: nacos/nacos-server
    networks:
      - api-net
    ports:
      - 28848:8848
    environment:
      - MODE=standalone
    mem_limit: 512m
    volumes:
      - ./data/nacos/data:/home/nacos/data
      - ./data/nacos/logs:/home/nacos/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/"]
      interval: 10s
      timeout: 10s
      retries: 5

  mysql:
    image: mysql
    restart: always
    networks:
      - api-net
    ports:
      - 23306:3306
    environment:
      MYSQL_ROOT_PASSWORD: yhapimysql
      MYSQL_DATABASE: yhapi
      TZ: Asia/Shanghai
      MYSQLD__sql_mode: "TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - /root/docker-compose/mysql/data:/var/lib/mysql
      - /root/docker-compose/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - "--max_connections=1000"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
      - "--default-authentication-plugin=mysql_native_password"
      - "--sql_mode=TRADITIONAL,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent localhost:3306 >/dev/null || exit 1"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
  #  ok
  redis:
    image: redis
    networks:
      - api-net
    ports:
      - 26379:6379
    volumes:
      - ./data/redis:/data
    #    depends_on:
    #     nacos:
    #       condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  main:
    image: 1583427850/yhapi-main:5
    ports:
      - 7529:7529
    networks:
      - api-net
    depends_on:
      nacos:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7529/"]
      interval: 10s
      timeout: 10s
      retries: 10

  pay:
    image: 1583427850/yhapi-pay:5
    networks:
      - api-net
    ports:
      - 7532:7532
    depends_on:
      nacos:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7532/ping"]
      interval: 10s
      timeout: 10s
      retries: 10


  generator:
    image: 1583427850/yhapi-template-generator:5
    networks:
      - api-net
    ports:
      - 7533:7533
    depends_on:
      nacos:
        condition: service_healthy
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7533/ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  #0.0005
  gateway:
    image: 1583427850/yhapi-gateway:5
    networks:
      - api-net
    ports:
      - 8081:8081
    depends_on:
      main:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  audit:
    image: 1583427850/yhapi-audit:5
    networks:
      - api-net
    ports:
      - 7530:7530
    depends_on:
      main:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7530/ping"]
      interval: 10s
      timeout: 10s
      retries: 10

  gpt:
    image: 1583427850/yhapi-gpt:5
    networks:
      - api-net
    ports:
      - 7531:7531
    depends_on:
      audit:
        condition: service_healthy

  api-backed-gateway:
    image: 1583427850/yhapi-backed-gateway:5
    networks:
      - api-net
    ports:
      - 9529:9529
    depends_on:
      nacos:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9529/"]
      interval: 10s
      timeout: 10s
      retries: 10

#  #  ok
  weather-interface:
    image: 1583427850/yhapi-interface-weather:5
    ports:
      - 8085:8085
    networks:
      - api-net
    volumes:
      - ./data:/etc/api/data
      - ./config:/etc/api/config
    depends_on:
      nacos:
        condition: service_healthy

  #  用来测试是否可以调用接口
#  test-interface:
#    image: 1583427850/yhapi-interface-test:5
#    ports:
#      - 7601:7601
#    networks:
#      - api-net

#  front:
#    image: 1583427850/api-front:3
#    ports:
#      - 80:80
#    networks:
#      - api-net
#    depends_on:
#      main:
#        condition: service_healthy
networks:
  api-net:

